[build-system]
requires = [
    "setuptools>=68"
]
build-backend = "setuptools.build_meta"

[project]
name = "cputorch"
version = "0.5.3"
description = "CPU-focused tensor and neural network engine written in C++"
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"

[project.urls]
Homepage = "https://github.com/Mangono1/minitorch"
Repository = "https://github.com/Mangono1/minitorch"
